name: learn-github-actions for build armbian
run-name: ${{github.action}} build armbian
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_release:
        description: "Select OS release:"
        required: false
        default: "jammy"
        type: choice
        options:
          - jammy
          - bullseye
          - lunar
          - bookworm
jobs:
  check-bats-version:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4
      - name: setup node
        id: setup_node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: install bats
        id: install_bats
        run: npm install -g bats
      - name: print version
        id: print_version
        run: bats -v
      - name: print input env
        id: print_env
        run: |
          echo "::group::log group 1"
          echo Select OS release:${{inputs.set_release}}
          echo "::endgroup::"
          echo "::group::log group 2"
          docker --version
          docker image ls
          docker container ls
          echo "::endgroup::"
      - name: Generate list using Markdown
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY