name: learn-github-actions
run-name: ${{github.action}} build armbian
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_release:
        description: "Select OS release:"
        required: false
        default: "jammy"
        type: choice
        options:
          - jammy
          - bullseye
          - lunar
          - bookworm
jobs:
  check-bats-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v